[package]
name = "mlp"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = { version = "1.24.0", features = ["alloc_uninit", "extern_crate_alloc", "zeroable_maybe_uninit"] }
derive_more = { version="2.0.1", features=["full"] }
faer = "0.23.2"
rand = "0.9.2"
rayon = "1.11.0"

[lib]
